### ISSUE TITLE
Frame upper line/dropshadow

### ISSUE THREAD

**Issue by bronze** [Spiderpig86/MaterialDark#1]
Hey there

I got this white outline on my top frame, has anyone seen this?
Mac Mojave 10.14.1 // Chrome Version 70.0.3538.102
Edit: using the new dark mode feature on the OS

![screen shot 2018-11-14 at 23 38 17](https://user-images.githubusercontent.com/170220/48524265-e02aa700-e866-11e8-9fb0-ff3df87b4c94.png)  
![screen shot 2018-11-14 at 23 38 32](https://user-images.githubusercontent.com/170220/48524264-e02aa700-e866-11e8-9fce-af20df4dcc13.png)

**Comment by Spiderpig86** [comment]
Thanks for the report. I'll take a look into it and see if it is something I can tweak. I do see it on Windows, but it is not as pronounced.

**Comment by Spiderpig86** [comment]
![image](https://user-images.githubusercontent.com/2801187/139332546-768ca1eb-3789-4180-af5e-b012b75ce683.png)

Wow, it's been almost 3 years. For the sake of posterity, it looks like the issue should've been resolved with later versions of Chrome. This is what it looks like on Chrome/94.0.4606.81 running on Big Sur. Resolving.
