### ISSUE TITLE
Chrome 74.0.3729.108 downloads bar unreadable

### ISSUE THREAD

**Issue by marekkaczkowski** [Spiderpig86/MaterialDark#2]
After the last update to Chrome 74.0.3729.108 on Windows 10 downloads bar looks unreadable

![2019-04-30 10_08_28-Input_ Fonts for Code — Download](https://user-images.githubusercontent.com/273831/56948381-40b95200-6b30-11e9-82a0-87477c262c12.png)

**Comment by Spiderpig86** [comment]
It looks like what Chrome is doing is using the native theme color on your system to style the downloads bar. If you try changing the system theme from light to dark, I think it might resolve the issue. For the time being, I will look into how to fix this. Chrome loves to break things.

**Comment by marekkaczkowski** [comment]
That did the trick :relaxed: Thanks!

![2019-04-30 15_09_28-Settings](https://user-images.githubusercontent.com/273831/56963799-167c8a00-6b5a-11e9-8651-7f7259524d05.png)
